from collections.abc import Sequence

def add(a: int, b: int) -> int: ...
def checked_sum(values: Sequence[int]) -> int: ...
def lower_bound(values: Sequence[int], target: int) -> int: ...
def binary_search(values: Sequence[int], target: int) -> int | None: ...
